# Generated by Django 5.2.15 on 2026-07-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Id', models.CharField(max_length=10)),
                ('Emp_name', models.CharField(max_length=50)),
                ('desiganation', models.CharField(max_length=40)),
                ('salary', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
